name: Build

on:
  push:
    branches:
      - master
      - windows-store-distribution
  create:
    tags: [v*]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: npx gulp build-ci

      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Release on version tag
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          skip_build: true

      - uses: actions/upload-artifact@v2
        with:
          name: SpaceEye-${{ matrix.os }}
          path: |
            release/*.dmg
            release/*.exe
